### ISSUE TITLE
Downmix uses int16 when calculating mean, this causes integer overflows.

### ISSUE THREAD

**Issue by Frans-Lukas** [CPJKU/SuperFlux#1]
When going through the code I noticed that the downmix method sets the dtype to int16. When a stereo signal has values close the int16_max/int16_min this causes an integer overflow. For example if the values of a sample is -32,760, -32,760 the mean overflows to 8. 

```
val = [-32760, -32760]
print(np.mean(val, dtype=np.dtype(np.int16)))
```
Prints
`8`

The relevant code is:
```
    def downmix(self):
        """
        Down-mix the audio signal to mono.

        """
        if self.num_channels > 1:
            self.audio = np.mean(self.audio, axis=-1, dtype=self.audio.dtype)
```

**Comment by superbock** [comment]
This code is obsolete and superseded by the implementation which comes with [madmom](https://github.com/CPJKU/madmom).

**Comment by Frans-Lukas** [comment]
Okay, thank you.
